name: Build, Test, and Release Debian Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: debian:12
      options: --privileged

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          build-essential \
          debhelper \
          devscripts \
          clang \
          g++ \
          libfmt-dev \
          fakeroot \
          lintian \
          git \
          ca-certificates

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Generate debian/changelog
      run: |
        export DEBFULLNAME="Fauzy Madani"
        export DEBEMAIL="fauzymadani3@gmail.com"

        # Get version from tag or fallback
        VERSION="${GITHUB_REF##*/}"
        VERSION="${VERSION#v}"  # remove 'v' prefix if exists
        VERSION="${VERSION:-1.0.0}-1"

        dch --create -v "$VERSION" --package salut --distribution bookworm \
          "Automated CI build for version $VERSION"

    - name: Build .deb package
      run: |
        dpkg-buildpackage -us -uc

    - name: Lintian check (optional)
      run: |
        lintian ../salut_*.deb || true

    - name: Upload .deb as artifact
      uses: actions/upload-artifact@v3
      with:
        name: salut-deb
        path: ../salut_*.deb

  upload-release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'release'

    steps:
    - name: Download built .deb
      uses: actions/download-artifact@v3
      with:
        name: salut-deb
        path: .

    - name: Upload .deb to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: salut_*.deb
