name: Build and Release Debian Package

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up build environment (Debian)
        run: |
          docker run --rm -v "$PWD:/src" -w /src debian:12 bash -c '
            apt-get update &&
            apt-get install -y \
              build-essential \
              debhelper \
              devscripts \
              clang \
              g++ \
              libfmt-dev \
              fakeroot \
              lintian &&
            export DEBFULLNAME="Fauzy Madani" &&
            export DEBEMAIL="fauzymadani3@gmail.com" &&
            VERSION="${GITHUB_REF##*/}" &&
            VERSION="${VERSION#v}" &&
            VERSION="${VERSION:-1.0.0}-1" &&
            dch --create -v "$VERSION" --package salut --distribution bookworm \
              "Automated CI build for version $VERSION" &&
            dpkg-buildpackage -us -uc &&
            mkdir -p out &&
            cp ../salut_*.deb out/
          '

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: salut-deb
          path: ./out/salut_*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download built .deb
        uses: actions/download-artifact@v4
        with:
          name: salut-deb
          path: .

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: salut_*.deb
