name: Build and Release Debian Package

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:12

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            debhelper \
            devscripts \
            clang \
            g++ \
            libfmt-dev \
            fakeroot \
            lintian \
            git \
            ca-certificates

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate changelog
        run: |
          export DEBFULLNAME="Fauzy Madani"
          export DEBEMAIL="fauzymadani3@gmail.com"

          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          VERSION="${VERSION:-1.0.0}-1"

          dch --create -v "$VERSION" --package salut --distribution bookworm \
            "Automated CI build for version $VERSION"

      - name: Build .deb package
        run: |
          dpkg-buildpackage -us -uc

      - name: Save .deb artifact
        run: |
          mkdir -p /tmp/deb
          cp ../salut_*.deb /tmp/deb/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: salut-deb
          path: /tmp/deb/salut_*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: salut-deb
          path: .

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: salut_*.deb
